from collections import defaultdict

import nonebot
from arknights_game_model.game_data import game_data
from arknights_game_model.utils import escape_description, find_dollar_tags
from nonebot import MatcherGroup
from nonebot.adapters import Message
from nonebot.params import CommandArg, RegexGroup
from nonebot.plugin import PluginMetadata

from .config import plugin_config

driver = nonebot.get_driver()
default_command_start: str = tuple(driver.config.command_start)[0]

help_str: str = f"""
【可用命令】
- {default_command_start}基建技能 <干员名称>    # 查询基建技能
- {default_command_start}术语释义 <术语>    # 查询术语释义
- {default_command_start}<干员名称>满练消耗    # 查询干员满练消耗
""".strip()

__plugin_meta__ = PluginMetadata(
    name="明日方舟数据",
    description="明日方舟数据查询，提供基建技能、术语释义、满练消耗查询等各种实用功能。",
    usage=help_str,
)


@driver.on_startup
def on_startup_func() -> None:
    game_data.load_data(**plugin_config.model_dump())


ELITE_LEVEL_DICT = {
    0: "精零",
    1: "精一",
    2: "精二",
}


def get_term_ids(initial_queue: list[str]) -> list[str]:
    """根据字符串广度优先搜索术语 ID 列表"""
    term_ids = []
    queue = initial_queue.copy()
    visited = set()

    while queue:
        term_id = queue.pop(0)
        if term_id in visited:
            continue

        visited.add(term_id)

        if term_id not in game_data.raw_data.excel.gamedata_const.term_description_dict:
            continue  # 有时候会因为解包库更新不及时导致找不到术语

        term_ids.append(term_id)
        term_description = (
            game_data.raw_data.excel.gamedata_const.term_description_dict[
                term_id
            ].description
        )
        queue.extend(find_dollar_tags(term_description))

    return term_ids


arknights_matcher_group = MatcherGroup(priority=5, block=False)
base_skill = arknights_matcher_group.on_regex(r"^(.+)基建技能$|^基建技能\s*(.+)$")
terminology = arknights_matcher_group.on_command("术语释义")
evolve_cost = arknights_matcher_group.on_regex(r"^(.+)(?:满练|拉满)消耗$")


@base_skill.handle()
async def base_skill_func(
    regex_group: tuple[str, None] | tuple[None, str] = RegexGroup(),
):
    character_str = regex_group[0] if regex_group[0] is not None else regex_group[1]

    try:
        character = game_data.characters.by_name(character_str)
    except KeyError:
        await base_skill.finish(f"未找到名称为“{character_str}”的干员")

    initial_queue: list[str] = []

    lines: list[str] = []
    lines.append(f"干员 {character.id}（{character.name}）")
    lines.append("________________")

    for skill_num, buff_char_item in enumerate(
        game_data.raw_data.excel.building_data.chars[character.id].buff_char, start=1
    ):
        if buff_char_item.buff_data:
            lines.append("")
            lines.append(f"/- 基建技能 {skill_num} -/")

            for buff_data_item in buff_char_item.buff_data:
                skill_id = buff_data_item.buff_id
                skill = game_data.raw_data.excel.building_data.buffs[skill_id]
                lines.append("")
                lines.append(
                    f"【{skill.buff_name}】{ELITE_LEVEL_DICT.get(buff_data_item.cond.phase)} {buff_data_item.cond.level} 级解锁"
                )
                lines.append(escape_description(skill.description))
                initial_queue.extend(find_dollar_tags(skill.description))

    term_id_list = get_term_ids(initial_queue)
    if term_id_list:
        lines.append("")
        lines.append("")
        lines.append("相关术语释义")
        lines.append("________________")
        lines.append("")
        for term_id in term_id_list:
            term = game_data.raw_data.excel.gamedata_const.term_description_dict[
                term_id
            ]
            lines.append("")
            lines.append(f"/- {term.term_name} -/")
            lines.append("")
            lines.append(escape_description(term.description))

    lines.append("")
    lines.append("________________")
    lines.append("# Generated by BioBot")
    lines.append("# Made by bilibili@Bio-Hazard")
    lines.append("https://space.bilibili.com/37179776")

    await base_skill.finish("\n".join(lines))


@terminology.handle()
async def terminology_func(message: Message = CommandArg()):
    query_term_name_list = message.extract_plain_text().strip().split()
    if not query_term_name_list:
        await terminology.finish(help_str)

    term_name_to_ids = defaultdict(list)
    for term in game_data.raw_data.excel.gamedata_const.term_description_dict.values():
        if term.term_name in query_term_name_list:
            term_name_to_ids[term.term_name].append(term.term_id)

    lines: list[str] = []
    lines.append(f"术语释义")
    lines.append("________________")
    for term_name in query_term_name_list:
        if not term_name_to_ids.get(term_name, []):
            lines.append("")
            lines.append(f"/- {term_name} -/")
            lines.append("")
            lines.append(f"未找到术语 {term_name} 的释义")
        else:
            for term_id in term_name_to_ids[term_name]:
                term = game_data.raw_data.excel.gamedata_const.term_description_dict[
                    term_id
                ]
                lines.append("")
                lines.append(f"/- {term.term_name} -/")
                lines.append("")
                lines.append(escape_description(term.description))

    initial_queue = sum(term_name_to_ids.values(), [])
    term_id_list = get_term_ids(initial_queue)
    for term_id in term_id_list:
        if term_id in initial_queue:
            continue
        term = game_data.raw_data.excel.gamedata_const.term_description_dict[term_id]
        lines.append("")
        lines.append(f"/- {term.term_name} -/")
        lines.append("")
        lines.append(escape_description(term.description))
    lines.append("")
    lines.append("________________")
    lines.append("# Generated by BioBot")
    lines.append("# Made by bilibili@Bio-Hazard")
    lines.append("https://space.bilibili.com/37179776")

    await terminology.finish("\n".join(lines))


@evolve_cost.handle()
async def evolve_cost_func(regex_group: tuple[str] = RegexGroup()):
    character_str = regex_group[0]

    lines: list[str] = []

    if character_str.rstrip("干员") in ("全", "所有", "全部"):
        item_info_list = (
            game_data.characters.全干员拉满消耗().combine().sort_by_sort_id()
        )

        lines.append("/- 全干员拉满消耗 -/")
        lines.append("")

    else:
        try:
            character = game_data.characters.by_name(character_str)
        except KeyError:
            await evolve_cost.finish(f"未找到名称为“{character_str}”的干员")

        item_info_list = character.养成消耗().combine().sort_by_sort_id()

        lines.append(f"干员 {character.id}（{character.name}）")
        lines.append("________________")
        lines.append("")
        lines.append("/- 拉满消耗 -/")
        lines.append("")

    yituliu_item_value = item_info_list.yituliu_item_value(strict=False)

    lines.extend(str(item_info_list).split())

    lines.append("")
    lines.append(f"相当于 {yituliu_item_value:.2f} 理智")
    lines.append("")
    lines.append("________________")
    lines.append("# 物品价值数据来自 明日方舟一图流 - 物品价值表")
    lines.append("https://ark.yituliu.cn/material/value")
    lines.append("")
    lines.append("# Generated by BioBot")
    lines.append("# Made by bilibili@Bio-Hazard")
    lines.append("https://space.bilibili.com/37179776")

    await evolve_cost.finish("\n".join(lines))
