from io import BytesIO

import aiohttp
from PIL import Image, ImageDraw, ImageFont
from PIL.Image import Image as PILImage
from PIL.ImageDraw import ImageDraw as PILImageDraw
from PIL.ImageFont import FreeTypeFont

fontpath = "data/maimai/fonts/SourceHanSans.otf"

category = {
    'POPSアニメ': 'anime',
    'maimai': 'maimai',
    'niconicoボーカロイド': 'niconico',
    '東方Project': 'touhou',
    'ゲームバラエティ': 'game',
    'オンゲキCHUNITHM': 'ongeki'
}


def draw_text(img_pil, text, offset_x) -> None:
    draw: PILImageDraw = ImageDraw.Draw(img_pil)
    font: FreeTypeFont = ImageFont.truetype(fontpath, 48)
    width, height = draw.textsize(text, font)
    x = 5
    if width > 390:
        font = ImageFont.truetype(fontpath, int(390 * 48 / width))
        width, height = draw.textsize(text, font)
    else:
        x = int((400 - width) / 2)
    draw.rectangle((x + offset_x - 2, 360,
                    x + 2 + width + offset_x, 360 + height * 1.2),
                   fill=(0, 0, 0, 255))
    draw.text((x + offset_x, 360), text, font=font, fill=(255, 255, 255, 255))


def text_to_image(text: str) -> PILImage:
    font: FreeTypeFont = ImageFont.truetype(fontpath, 24)
    padding: int = 10
    margin: int = 4
    text_list: list[str] = text.split('\n')
    max_width: int = 0
    h: int = 0
    for text in text_list:
        w, h = font.getsize(text)
        max_width: int = max(max_width, w)
    wa: int = max_width + padding * 2
    ha: int = h * len(text_list) + margin * (len(text_list) - 1) + padding * 2
    i: PILImage = Image.new('RGB', (wa, ha), color=(255, 255, 255))
    draw: PILImageDraw = ImageDraw.Draw(i)
    for j in range(len(text_list)):
        text = text_list[j]
        draw.text((padding, padding + j * (margin + h)), text, font=font, fill=(0, 0, 0))
    return i


def image_to_bytesio(img: PILImage, format='PNG') -> BytesIO:
    bytesio = BytesIO()
    img.save(bytesio, format)
    bytesio.seek(0)
    return bytesio


async def get_user_logo(qq: int) -> PILImage:
    async with aiohttp.request('GET', f'http://q1.qlogo.cn/g?b=qq&nk={qq}&s=100') as response:
        return Image.open(BytesIO(await response.read()))


def get_cover_len4_id(music_id: str) -> str:
    num = int(music_id)
    if num > 10000:
        num -= 10000
    return f'{num:04d}'


# async def get_cover_pic(music_id: str) -> bytes:
#     if (cover_path := data_path / 'mai/cover' / f'{get_cover_len4_id(music_id)}.png').exists():
#         return cover_path.read_bytes()
#     else:
#         async with aiohttp.request('GET', f'https://www.diving-fish.com/covers/{get_cover_len4_id(music_id)}.png') as response:
#             return await response.read()


# async def download_music_pictrue(id: int | str) -> bytes:
#     try:
#         len4id = get_cover_len4_id(id)
#         if os.path.exists(file := os.path.join(static, 'mai', 'cover', f'{len4id}.png')):
#             return file
#         async with httpx.AsyncClient() as client:
#             r = await client.get(f"https://www.diving-fish.com/covers/{len4id}.png")
#             if r.status_code == 200:
#                 return BytesIO(r.content)
#             else:
#                 return os.path.join(static, 'mai', 'cover', '0000.png')
#     except:
#         return os.path.join(static, 'mai', 'cover', '0000.png')


# async def draw_music_info(music: Music) -> Image.Image:
#     image = Image.open(pic_path / 'music_bg.png').convert('RGBA')
#     genre = Image.open(pic_path / f'music-{category[music.genre]}.png')
#     cover = Image.open(cover_path / f'{get_cover_len4_id(music.id)}.png').resize((360, 360))
#     ver = Image.open(pic_path / f'{music.type}.png').resize((94, 35))
#     line = Image.new('RGBA', (400, 2), (255, 255, 255, 255))

#     image.alpha_composite(genre, (150, 170))
#     image.alpha_composite(cover, (170, 260))
#     image.alpha_composite(ver, (435, 585))
#     image.alpha_composite(line, (150, 710))

#     draw = ImageDraw.Draw(image)
#     tb = DrawText(draw, TBFONT)
#     sy = DrawText(draw, SIYUAN)

#     tb.draw(200, 195, 24, music.id, anchor='mm')
#     sy.draw(410, 195, 22, music.genre, anchor='mm')
#     sy.draw_partial_opacity(350, 660, 30, music.title, 1, anchor='mm')
#     sy.draw_partial_opacity(350, 690, 12, music.artist, 1, anchor='mm')
#     sy.draw_partial_opacity(150, 725, 15, f'Version: {music.version}', 1, anchor='lm')
#     sy.draw_partial_opacity(550, 725, 15, f'BPM: {music.bpm}', 1, anchor='rm')
#     for n, i in enumerate(list(map(str, music.ds))):
#         if n == 4:
#             color = (195, 70, 231, 255)
#         else:
#             color = (255, 255, 255, 255)
#         tb.draw(160 + 95 * n, 814, 25, i, color, 'mm')
#     sy.draw(350, 980, 14, f'Designed by Yuri-YuzuChaN | Generated by {BOTNAME} BOT', (255, 255, 255, 255), 'mm', 1, (159, 81, 220, 255))
#     return image
